// product_data.dart
import 'product.dart';

final List<Product> products = [
  Product(image: 'big3.jpg', name: 'Big chips', price: 15.0),
  Product(image: 'big4.jpg', name: 'Big chips', price: 15.0),
  Product(image: 'big5.jpg', name: 'Big chips', price: 15.0),
  Product(image: 'ex1.jpg', name: 'Tiger chips', price: 15.0),
  Product(image: 'ex2.jpg', name: 'Tiger chips', price: 15.0),
  Product(image: 'ti1.jpg', name: 'Tiger chips', price: 10.0),
  Product(image: 'flaminco.jpg', name: 'Flaminco', price: 10.0),
  Product(image: 'friday1.jpg', name: 'Ice Cream', price: 10.0),
  Product(image: 'friday2.jpg', name: 'Ice Cream', price: 10.0),
  Product(image: 'friday3.jpg', name: 'Ice Cream', price: 10.0),
  Product(image: 'friday4.jpg', name: 'Ice Cream', price: 10.0),
  Product(image: 'friday5.jpg', name: 'Ice Cream', price: 10.0),
  Product(image: 'friday6.jpg', name: 'Ice Cream', price: 10.0),
  Product(image: 'friday7.jpg', name: 'Ice Cream', price: 10.0),
  Product(image: 'friday8.jpg', name: 'Ice Cream', price: 10.0),
  Product(image: 'friday9.jpg', name: 'Ice Cream', price: 10.0),
  Product(image: 'friday10.jpg', name: 'Ice Cream', price: 10.0),
  Product(image: 'friday11.jpg', name: 'Ice Cream', price: 10.0),
  Product(image: 'friday12.jpg', name: 'Ice Cream', price: 10.0),
  Product(image: 'friday13.jpg', name: 'Ice Cream', price: 10.0),
  Product(image: 'friday14.jpg', name: 'Ice Cream', price: 15.0),
  Product(image: 'Spero1.jpg', name: 'Spero spates', price: 15.0),
  Product(image: 'Spero2.jpg', name: 'Spero spates', price: 15.0),
  Product(image: 'Spero3.jpg', name: 'Spero spates', price: 15.0),
  Product(image: 'Spero4.jpg', name: 'Spero spates', price: 15.0),
  Product(image: 'Spero5.jpg', name: 'Spero spates', price: 15.0),
  Product(image: 'v75.jpg', name: 'V7', price: 15.0),
  Product(image: 'v74.jpg', name: 'V7', price: 15.0),
  Product(image: 'v73.jpg', name: 'V7', price: 15.0),
  Product(image: 'v72.jpg', name: 'V7', price: 15.0),
  Product(image: 'v71.jpg', name: 'V7', price: 8.0),
  Product(image: 'bigc.jpg', name: 'Big cola', price: 8.0),
  Product(image: 'Best.jpg', name: 'Best juice', price: 8.0),
];
